package com.sedsoftware.bulbmatch.compose.theme

import androidx.compose.ui.graphics.Color

internal val WarmYellowLight = Color(0xFF765A00)
internal val OnWarmYellowLight = Color(0xFFFFFFFF)
internal val WarmYellowContainerLight = Color(0xFFFFE08A)
internal val OnWarmYellowContainerLight = Color(0xFF251A00)
internal val NeutralBackgroundLight = Color(0xFFFBF9F4)
internal val NeutralSurfaceLight = Color(0xFFFFFBFF)
internal val NeutralOnSurfaceLight = Color(0xFF201E19)
internal val NeutralVariantLight = Color(0xFFECE5D8)
internal val NeutralOnVariantLight = Color(0xFF4D473D)
internal val OutlineLight = Color(0xFF7E7668)

internal val WarmYellowDark = Color(0xFFF1C84B)
internal val OnWarmYellowDark = Color(0xFF3D2F00)
internal val WarmYellowContainerDark = Color(0xFF594400)
internal val OnWarmYellowContainerDark = Color(0xFFFFE08A)
internal val NeutralBackgroundDark = Color(0xFF15130F)
internal val NeutralSurfaceDark = Color(0xFF15130F)
internal val NeutralOnSurfaceDark = Color(0xFFEAE2D6)
internal val NeutralVariantDark = Color(0xFF4D473D)
internal val NeutralOnVariantDark = Color(0xFFD1C5B4)
internal val OutlineDark = Color(0xFF998F80)

internal val SuccessLight = Color(0xFF1F6B43)
internal val SuccessContainerLight = Color(0xFFC1F1D2)
internal val OnSuccessContainerLight = Color(0xFF002112)
internal val SuccessDark = Color(0xFFA5D5B8)
internal val SuccessContainerDark = Color(0xFF07512F)
internal val OnSuccessContainerDark = Color(0xFFC1F1D2)

internal val WarningLight = Color(0xFF765A00)
internal val WarningContainerLight = Color(0xFFFFE08A)
internal val OnWarningContainerLight = Color(0xFF251A00)
internal val WarningDark = Color(0xFFF1C84B)
internal val WarningContainerDark = Color(0xFF594400)
internal val OnWarningContainerDark = Color(0xFFFFE08A)

internal val ConflictLight = Color(0xFF9A3A24)
internal val ConflictContainerLight = Color(0xFFFFDAD0)
internal val OnConflictContainerLight = Color(0xFF3B0900)
internal val ConflictDark = Color(0xFFFFB5A3)
internal val ConflictContainerDark = Color(0xFF7C210F)
internal val OnConflictContainerDark = Color(0xFFFFDAD0)
